import { jsPDF } from 'jspdf';

type CertificatePayload = {
  studentName: string;
  eventTitle: string;
  eventDate?: string;
  certificateCode: string;
  issuedAt?: string;
};

const formatDate = (date?: string) => {
  if (!date) return 'N/A';
  const value = new Date(date);
  if (Number.isNaN(value.getTime())) return date;
  return value.toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
};

const sanitizeFileName = (name: string) => name.replace(/[^a-z0-9-]/gi, '_').toLowerCase();

export const downloadParticipationCertificate = (payload: CertificatePayload) => {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFillColor(249, 250, 251);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(3);
  doc.rect(24, 24, pageWidth - 48, pageHeight - 48);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(34);
  doc.text('Certificate of Participation', pageWidth / 2, 120, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(16);
  doc.text('This is to certify that', pageWidth / 2, 175, { align: 'center' });

  doc.setFont('times', 'bold');
  doc.setFontSize(36);
  doc.text(payload.studentName, pageWidth / 2, 225, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(15);
  doc.text('has successfully participated in', pageWidth / 2, 260, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.text(payload.eventTitle, pageWidth / 2, 295, { align: 'center', maxWidth: pageWidth - 140 });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(13);
  doc.text(`Event Date: ${formatDate(payload.eventDate)}`, pageWidth / 2, 332, { align: 'center' });
  doc.text(`Issued On: ${formatDate(payload.issuedAt)}`, pageWidth / 2, 352, { align: 'center' });

  const verificationUrl = `${window.location.origin}/verify-certificate?code=${encodeURIComponent(payload.certificateCode)}`;
  doc.setFontSize(12);
  doc.text(`Certificate ID: ${payload.certificateCode}`, pageWidth / 2, 400, { align: 'center' });
  doc.text(`Verification URL: ${verificationUrl}`, pageWidth / 2, 420, { align: 'center' });

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(11);
  doc.text('Digitally generated by CampusEvents', pageWidth / 2, pageHeight - 45, { align: 'center' });

  const fileName = `certificate_${sanitizeFileName(payload.studentName)}_${sanitizeFileName(payload.eventTitle)}.pdf`;
  doc.save(fileName);
};
